global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'load-balancer'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['load-balancer:8080']

  - job_name: 'api-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'api-service-0:8081'
          - 'api-service-1:8081'
          - 'api-service-2:8081'
          - 'api-service-3:8081'
